### ISSUE TITLE
smplx

### ISSUE THREAD

**Issue by wolf943134497** [geopavlakos/TexturePose#1]
Hi @geopavlakos   Thanks for your great work!

https://github.com/vchoutas/smplx/trunk/smplx   is invalid? 
smplx can not install by pip  because of python2.  How to install smplx in your projects!
Thanks!

**Comment by AndreyStille** [comment]
> Hi @geopavlakos Thanks for your great work!
> 
> https://github.com/vchoutas/smplx/trunk/smplx is invalid?
> smplx can not install by pip because of python2. How to install smplx in your projects!
> Thanks!

Hello. Can you please help, if you have solved this issue? I faced the same. Have you found the appropriate smplx?
