### ISSUE TITLE
where can I get these files?

### ISSUE THREAD

**Issue by MasonForFun** [geopavlakos/TexturePose#2]
Hi,
Thanks for the excellent project. I want to run demo.py, but it seems the following files is missing.

1. neutral_smpl_mean_params.h5

2. SMPL_NEUTRAL.pkl 
Is this file smplify's smplify_public/code/models/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl?

3. smpl_faces.npy

4. cocoplus_regressor.npy

can you give some suggestion?

**Comment by geopavlakos** [comment]
You can get the first and the last two files by running the `fetch_data.sh` script (I have updated the links, so if you had problems before, the links should be correct now). Regarding the second file, this is indeed the neutral SMPL model, provided by the SMPLify code.

**Comment by wolf943134497** [comment]
Hi @geopavlakos @MasonForFun  Have you ever met this problem?
python demo.py --checkpoint=data/texturepose_checkpoint.pth --img=examples/im1025.jpg
Traceback (most recent call last):
  File "demo.py", line 139, in <module>
    pred_verts = smpl_gen(global_orient=pred_rotmat3[:, [0]], body_pose=pred_rotmat3[:, 1:], betas=pred_shape3, pose2rot=False).vertices
  File "/home/anaconda2/envs/tf-g/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/TexturePose/models/smpl.py", line 33, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/smplx/body_models.py", line 374, in forward
  File "build/bdist.linux-x86_64/egg/smplx/lbs.py", line 195, in lbs
RuntimeError: size mismatch, m1: [1 x 639], m2: [207 x 20670] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266


smplx problem? the smplx version provided by @geopavlakos  is valid!

or the pytorch problem?  change the pytorch version or change the TexturePose source code?

Did you run the demo successfully?

**Comment by MasonForFun** [comment]
> You can get the first and the last two files by running the `fetch_data.sh` script (I have updated the links, so if you had problems before, the links should be correct now). Regarding the second file, this is indeed the neutral SMPL model, provided by the SMPLify code.

Hi geopavlakos, the problem is solved after update the links. Thanks for the help.

**Comment by MasonForFun** [comment]
> Hi @geopavlakos @MasonForFun Have you ever met this problem?
> python demo.py --checkpoint=data/texturepose_checkpoint.pth --img=examples/im1025.jpg
> Traceback (most recent call last):
> File "demo.py", line 139, in 
> pred_verts = smpl_gen(global_orient=pred_rotmat3[:, [0]], body_pose=pred_rotmat3[:, 1:], betas=pred_shape3, pose2rot=False).vertices
> File "/home/anaconda2/envs/tf-g/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/TexturePose/models/smpl.py", line 33, in forward
> smpl_output = super(SMPL, self).forward(*args, **kwargs)
> File "build/bdist.linux-x86_64/egg/smplx/body_models.py", line 374, in forward
> File "build/bdist.linux-x86_64/egg/smplx/lbs.py", line 195, in lbs
> RuntimeError: size mismatch, m1: [1 x 639], m2: [207 x 20670] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266
> 
> smplx problem? the smplx version provided by @geopavlakos is valid!
> 
> or the pytorch problem? change the pytorch version or change the TexturePose source code?
> 
> Did you run the demo successfully?

Yes, I run the dmo successfully.

**Comment by monacv** [comment]
@geopavlakos do you know how I can get the smpl_vertices.npy file?
