### ISSUE TITLE
visible points

### ISSUE THREAD

**Issue by wuneng** [geopavlakos/TexturePose#3]
Hi, thanks for share your code. I want to know how to get visible points of smpl, which is mentioned in your paper.

**Comment by jinx2018** [comment]
I have the same demand for how to calculate  the visibility of each point within 3d mesh~

**Comment by wuneng** [comment]
@jinx2018 I have finished it. If you still have  a demand,   just contact me(QQ6553947).

**Comment by AndreyStille** [comment]
> @jinx2018 I have finished it. If you still have a demand, just contact me(QQ6553947).
Hi. If you have some time could you please help? 
You mentioned that you have solved the issue. How can I get visible points on mesh ?
