### ISSUE TITLE
how to get human mesh with texture?

### ISSUE THREAD

**Issue by wolf943134497** [geopavlakos/TexturePose#4]
Hi @nkolot @geopavlakos  Thanks for your great work!
after run the demo.py, the results only shows the human mesh, how can I get the human mesh with texture?
Thanks!

**Comment by qzane** [comment]
The regression model part looks pretty good, looking forward to see the texture part.

**Comment by bumuthu** [comment]
Is there a way to get the texture as a .PNG or .JPG file?

**Comment by xhuan8** [comment]
Hi, anyone figure it out?
